- name: ACM Policy Automation
  hosts: all
  tasks:
    - name: ACM Policy is NonCompliant
      community.general.slack:
        token: "{{ slack_token }}"
        channel: "#grc-cluster-policy-violations"
        icon_url: https://www.ansible.com/favicon.ico
        color: danger
        blocks:
          - type: section
            text:
              type: mrkdwn
              text: |-
                *Policy Violation*
                Policy {{ policy_name }} in namespace {{ policy_namespace }} is NonCompliant
          - type: context
            elements:
            - type: mrkdwn
              text: |-
                *Advanced Cluster Management Hub*
                {{ cluster_name }}
            - type: mrkdwn
              text: |-
                *Clusters*
                NonCompliant Managed Clusters: {{ target_clusters }}

